"""new1234

Revision ID: 4f2ffdaa26ce
Revises: 3bd39b43c431
Create Date: 2025-04-10 10:23:35.661993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f2ffdaa26ce'
down_revision: Union[str, None] = '3bd39b43c431'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('invoices_user_id_fkey', 'invoices', type_='foreignkey')
    op.drop_column('invoices', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('invoices_user_id_fkey', 'invoices', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
